name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'App/**'
      - '.github/workflows/**'
      
  workflow_dispatch:
jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1       
        
  build:
    needs: prebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     
      - name: Install SonarCloud scanner
        shell: pwsh
        run: | 
          dotnet tool install --global dotnet-sonarscanner --version 5.4.1
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          dotnet-sonarscanner begin /k:"Elouel_DevopsPractice" /o:"elouel" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          dotnet restore App/DevopsTest/DevopsTest.csproj
          dotnet build App/DevopsTest/DevopsTest.csproj --configuration Release --no-restore
          dotnet test App/Tests/Tests.csproj --no-restore --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
         
  pack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./App/DevopsTest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.run_number }},${{ secrets.DOCKERHUB_USERNAME }}/app:latest

  scanimage:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest


  deploy:
    needs: scanimage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Change kubernetes configs
        shell: pwsh
        run: |
         (Get-Content -Path ${{ github.workspace }}/KubConfig/base/appDeployment.yml) |
          ForEach-Object {$_ -Replace 'elouel/app:[0-9]*', 'elouel/app:${{ github.run_number }}' } |
              Set-Content -Path ${{ github.workspace }}/KubConfig/base/appDeployment.yml
              
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Change config with the new version of the app" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
