name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'App/**'
      - '.github/workflows/**'

  workflow_dispatch:
jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1
    
 # This workflow contains a single job called "build"
  pack:
    # The type of runner that the job will run on
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./App/DevopsTest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.run_number }},${{ secrets.DOCKERHUB_USERNAME }}/app:latest

  scanimage:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest


  deploy:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Change kubernetes configs
        shell: pwsh
        run: |
          .\changeImageVersion.ps1 --image ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.run_number }
