name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'App/**'
      - '.github/workflows/**'

  workflow_dispatch:
jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps: 
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1
        
  build:
    needs: prebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'csharp'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Install dependencies
        run: dotnet restore  App/DevopsTest/DevopsTest.csproj

      - name: Build
        run: dotnet build App/DevopsTest/DevopsTest.csproj /p:UseSharedCompilation=false --configuration Release --no-restore
      
      - name: Test
        run: dotnet test App/Test/Tests.csproj --no-restore --no-build --verbosity normal

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
    
 # This workflow contains a single job called "build"
  pack:
    # The type of runner that the job will run on
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./App/DevopsTest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.run_number }},${{ secrets.DOCKERHUB_USERNAME }}/app:latest

  scanimage:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest


  deploy:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Change kubernetes configs
        shell: pwsh
        run: |
         (Get-Content -Path ${{ github.workspace }}/KubConfig/base/appDeployment.yml) |
          ForEach-Object {$_ -Replace 'elouel/app:[0-9]*', 'elouel/app:${{ github.run_number }}' } |
              Set-Content -Path ${{ github.workspace }}/KubConfig/base/appDeployment.yml
              
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
